# Change name and email of all commits in a github account
# Use the file "emails.list" generated by the script "list-all-users.py"
import sys
import os
import threading
from utils import *

FILE = 'emails.list'

def process_repo(repo, users, number, total, lock):
	name= repo.split("/")[-1].split(".")[0]
	print(f"\r\033[94m{number}/{total} ({name})\033[0m Clonning repo...")
	res = clone_repo(repo, name, lock)
	if res != 0:
		print(f"\r\033[94m{number}/{total} ({name})\033[0m Clonning repo... \033[91mERROR\033[0m")
		return
	
	# Move script
	res = os.system("cp git-rename.sh " + LOCAL_FOLDER + "/" + name + " >> " + LOG_FOLDER + "/" + name + ".log 2>&1")
	log_absolute = os.path.abspath(LOG_FOLDER + "/" + name + ".log")
	if res != 0:
		print(f"\r\033[94m{number}/{total} ({name})\033[0m Moving script... \033[91mERROR\033[0m")
		return
	
	print(f"\r\033[94m{number}/{total} ({name})\033[0m Clonning repo... \033[92mOK\033[0m")

	# Get all users for this repo
	users_repo = [user for user in users if repo in user.repo]
	print(f"\r\033[94m{number}/{total} ({name})\033[0m {len(users_repo)} users found")
	j = 1
	for user in users_repo:
		print(f"\r\033[94m{number}/{total} ({name})\033[0m \033[93m{j}/{len(users_repo)}\033[0m {user.email} -> {user.new_name} <{user.new_email}>...")
		# Change name and email
		res = os.system("sed -i -e \"s/OLD_EMAIL=.*/OLD_EMAIL=\\\"""" + user.email + """\\\"/\" """ + LOCAL_FOLDER + "/" + name + """/git-rename.sh""" + " >> " + log_absolute + " 2>&1")
		if res != 0:
			print(f"\r\033[94m{number}/{total} ({name})\033[0m \033[93m{j}/{len(users_repo)}\033[0m {user.email} -> {user.new_name} <{user.new_email}>... \033[91mERROR\033[0m")
			return
		res = os.system("sed -i -e \"s/CORRECT_NAME=.*/CORRECT_NAME=\\\"""" + user.new_name + """\\\"/\" """ + LOCAL_FOLDER + "/" + name + """/git-rename.sh""" + " >> " + log_absolute + " 2>&1")
		if res != 0:
			print(f"\r\033[94m{number}/{total} ({name})\033[0m \033[93m{j}/{len(users_repo)}\033[0m {user.email} -> {user.new_name} <{user.new_email}>... \033[91mERROR\033[0m")
			return
		res = os.system("sed -i -e \"s/CORRECT_EMAIL=.*/CORRECT_EMAIL=\\\"""" + user.new_email + """\\\"/\" """ + LOCAL_FOLDER + "/" + name + """/git-rename.sh""" + " >> " + log_absolute + " 2>&1")
		if res != 0:
			print(f"\r\033[94m{number}/{total} ({name})\033[0m \033[93m{j}/{len(users_repo)}\033[0m {user.email} -> {user.new_name} <{user.new_email}>... \033[91mERROR\033[0m")
			return

		# Launch script
		res = os.system("cd " + LOCAL_FOLDER + "/" + name + " && sh ./git-rename.sh" + " >> " + log_absolute + " 2>&1")
		if res != 0:
			print(f"\r\033[94m{number}/{total} ({name})\033[0m \033[93m{j}/{len(users_repo)}\033[0m {user.email} -> {user.new_name} <{user.new_email}>... \033[91mERROR\033[0m")
			return

		print(f"\r\033[94m{number}/{total} ({name})\033[0m \033[93m{j}/{len(users_repo)}\033[0m {user.email} -> {user.new_name} <{user.new_email}>... \033[92mOK\033[0m")
		j+=1
	

	# Push
	print(f"\r\033[94m{number}/{total} ({name})\033[0m Pushing...")
	res = os.system("cd " + LOCAL_FOLDER + "/" + name + " && git push --force" + " >> " + log_absolute + " 2>&1")
	if res != 0:
		print(f"\r\033[94m{number}/{total} ({name})\033[0m Pushing... \033[91mERROR\033[0m")
		return
	print(f"\r\033[94m{number}/{total} ({name})\033[0m Pushing... \033[92mOK\033[0m")
	
	# Delete repo folder
	print(f"\r\033[94m{number}/{total} ({name})\033[0m Deleting repo folder...")
	res = os.system("rm -rf " + LOCAL_FOLDER + "/" + name + " >> " + log_absolute + " 2>&1")
	if res != 0:
		print(f"\r\033[94m{number}/{total} ({name})\033[0m Deleting repo folder... \033[91mERROR\033[0m")
		return
	print(f"\r\033[94m{number}/{total} ({name})\033[0m Deleting repo folder... \033[92mOK\033[0m")
	

if __name__ == '__main__':

# Verify if CARREFUL_LINE is in the file
	if CARREFUL_LINE in open(FILE).read():
		print("Error: " + FILE + " is not ready for use (think to delete the carreful line before using this script)")
		exit(1)

	# Rm local folder
	os.system("rm -rf " + LOCAL_FOLDER)
	os.system("rm -rf " + LOG_FOLDER)

	# Read the file
	users = read_users(FILE)
	
	# Keep only user with modified name or email
	users = [user for user in users if user.modified()]

	# List off all repo to clone
	repos = []
	for user in users:
		for repo in user.repo:
			if repo not in repos:
				repos.append(repo)

	print("Found " + str(len(repos)) + " repositories to process")

	# Threads to process all repos
	threads = []
	i = 1
	lock = threading.Lock()
	for repo in repos:
		t = threading.Thread(target=process_repo, args=(repo, users, i, len(repos), lock))
		threads.append(t)
		t.start()
		i += 1